export { default as Header } from "./Header/HeaderContainer";
export { default as SideBar } from "./SideBar/SideBar";
export { default as Avatar } from "./Avatar/CustomeAvatar";
export { default as SettingPage } from "./SettingPage/SettingPage";
export { default as UsersRole } from "./UsersRole/UsersRoleContainer";
export { default as CreateProductPage } from "./CreateProductPage/CreateProductPage";
export { default as Shop } from "./Shop/Shop";
export { default as OneProductPage } from "./OneProductPage/OneProductPage";
export { default as Basket } from "./Basket/Basket";
